name: OpenResty Docker Image Publish

on:
  workflow_dispatch:
    inputs:
      OPENRESTY_VERSION:
        required: false
        type: string
        description: 'The openresty stable version ("W.X.Y.Z")'
      LUAROCKS_VERSION:
        required: false
        type: string
        description: 'The luarocks stable version ("W.X.Y")'
  repository_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get latest versions
      id: getVersion
      run: |
        if [ -z ${{ inputs.OPENRESTY_VERSION }} ]; then
          OPENRESTY_VERSION=$(wget -qO- -t1 -T2 https://api.github.com/repos/openresty/openresty/releases/latest | grep "tag_name" | awk -F "\"" '{printf $4}'| awk -F "v" '{printf $2}')
        else
          OPENRESTY_VERSION=${{ inputs.OPENRESTY_VERSION }}
        fi
        echo "openrestyVersion=$OPENRESTY_VERSION" >> $GITHUB_OUTPUT
        if [ -z ${{ inputs.LUAROCKS_VERSION }} ]; then
          LUAROCKS_VERSION=$(wget -qO- -t1 -T2 https://api.github.com/repos/luarocks/luarocks/tags | grep "name" | head -n 1 | awk -F "\"" '{printf $4}'| awk -F "v" '{printf $2}')
        else
          LUAROCKS_VERSION=${{ inputs.LUAROCKS_VERSION }}
        fi
        echo "luarocksVersion=$LUAROCKS_VERSION" >> $GITHUB_OUTPUT
     
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Login to AliYun Registry
      uses: docker/login-action@v3
      with:
        registry: registry.cn-chengdu.aliyuncs.com
        username: ${{ secrets.ALIYUN_USER }}
        password: ${{ secrets.ALIYUN_TOKEN }}

    - name: Build and Push Docker images
      uses: docker/build-push-action@v5
      with:
        file: Dockerfile
        context: .
        push: true
        build-args: |
          OPENRESTY_VERSION=${{ steps.getVersion.outputs.openrestyVersion }}
          LUAROCKS_VERSION=${{ steps.getVersion.outputs.luarocksVersion }}
        tags: |
          clion007/openresty:latest
          clion007/openresty:${{ steps.getVersion.outputs.openrestyVersion }}
          registry.cn-chengdu.aliyuncs.com/clion/openresty:latest
          registry.cn-chengdu.aliyuncs.com/clion/openresty:${{ steps.getVersion.outputs.openrestyVersion }}
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 2
