# Description: jellyfin version update checker

name: Jellyfin Update Checker

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */18 * * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Get latest version of jellyfin
      id: getVersion
      run: |
        version=$(wget -qO- -t1 -T2 https://api.github.com/repos/jellyfin/jellyfin/releases/latest | grep '"name"' | awk -F "\"" '{printf $4}')
        echo "curentVersion=$version" >> $GITHUB_OUTPUT

    - name: Compare jellyfin version
      id: cacheVersion
      uses: actions/cache@v4
      with:
        path: .curentVersion
        key: ${{ steps.getVersion.outputs.curentVersion }}

    - name: Save New Curent Version
      if: steps.cacheVersion.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getVersion.outputs.curentVersion }} | tee .curentVersion

    - name: Trigger build
      if: steps.cacheVersion.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v3
      with:
        event-type: Jellyfin Image Update
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 2
